server:
  port: 8085

spring:
  application:
    name: springappuser
  datasource:
    url: jdbc:mysql://localhost:3306/appturfdb?createDatabaseIfNotExist=true
    username: root
    password: examly
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: turfease-secret-key
  expirationMs: 86400000 # 1 day in milliseconds

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG

